apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-on-rails
resources:
  - all.yaml
commonLabels:
  app.kubernetes.io/name: agent-on-rails-website
  app.kubernetes.io/part-of: agent-on-rails
images:
  - name: ghcr.io/agent-on-rails/agent-on-rails-website
    newTag: cb3f6c6949a231e0dc4a4cb6d9d27de63ed19b91
